const Talks = [
  { _id: '1',
    date: '20.04',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '2',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'Approved',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '3',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '4',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'Approved',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '5',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '6',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '7',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'Approved',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '8',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '9',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '10',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '11',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '12',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'In Progress',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '13',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '14',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '15',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'New',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '16',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'Rejected',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },
  { _id: '17',
    date: 'integer',
    description: 'string',
    lang: 'Ukrainian',
    level: 'Begginer',
    status: 'Rejected',
    title: 'Talk',
    topic: 'Web development and Java Tech',
    type: 'string',
  },

];

export default Talks;
